export const DISASTER_CODE_MAP = {
  'Chemical': 0,
  'Coastal Storm': 1,
  'Dam/Levee Break': 2,
  'Drought': 3,
  'Earthquake': 4,
  'Fire': 5,
  'Fishing Losses': 6,
  'Flood': 7,
  'Freezing': 8,
  'Human Cause': 9,
  'Hurricane': 10,
  'Mud/Landslide': 11,
  'Other': 12,
  'Severe Ice Storm': 13,
  'Severe Storm(s)': 14,
  'Snow': 15,
  'Terrorist': 16,
  'Tornado': 17,
  'Toxic Substances': 18,
  'Tsunami': 19,
  'Typhoon': 20,
  'Volcano': 21
};
